version: '2'
services:
  web:
    image: graffitab/graffitab-server:0.1-local
    ports:
      - "8091:8091"
    depends_on:
      - redis
    links:
      - redis:redis
  redis:
    image: redis:3
    command: redis-server --requirepass $REDIS_PASSWORD