version: '2.1'
services:
  web:
    image: graffitab/graffitab-server:0.1-local
    ports:
      - "8091:8091"
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - redis:redis
      - mysql:mysql
    mem_limit: 400m
    #cpu_quota: 75000
  redis:
    image: graffitab/redis:3
    command: redis-server /usr/local/etc/redis/redis.conf --protected-mode no --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  mysql:
    image: graffitab/mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql-data:/var/lib/mysql
      - ./database/docker-startup:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - REDIS_PASSWORD=$REDIS_PASSWORD