version: '2'
services:
  web:
    image: graffitab/graffitab-server:0.1-local
    ports:
      - "8091:8091"
    depends_on:
      - mysql
      - redis
    links:
      - redis:redis
      - mysql:mysql
  redis:
    image: redis:3
    ports:
      - "6379:6379"
  mysql:
    image: mysql/mysql-server:5.6
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql-data:/var/lib/mysql
      - ./database/docker-startup:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=